project:
  type: website
  output-dir: docs

website:
  title: "my example website"
  navbar:
    background: "#005588"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Home Page"
          contents:
            - index.qmd
        - section: "My research"
          contents:
            - analyses/example_1.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



